name: CI Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Ensure ZIP file exists
      run: |
          if (-Not (Test-Path -Path .\bin\Chromium.zip)) {
            Write-Host "Chromium.zip not found"
            exit 1
          }
      shell: pwsh

    - name: Create directory for extraction
      run: |
              New-Item -ItemType Directory -Path "C:\CustomExtractPath" -Force
      shell: pwsh

    - name: Extract Chromium from ZIP
      run: |
              Expand-Archive -Path .\bin\Chromium.zip -DestinationPath "C:\CustomExtractPath"
      shell: pwsh

    - name: Verify extraction
      run: |
              if (-Not (Test-Path -Path "C:\CustomExtractPath\Application\chrome.exe")) {
                Write-Host "chrome.exe not found after extraction"
                exit 1
              }
      shell: pwsh

    - name: Run Chromium
      run: |
              Start-Process "C:\CustomExtractPath\Applicationchrome.exe"
      shell: pwsh

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Crypto-pro
      run: |
        cd .\bin
        .\CryptoPro-5.0.13000.exe
      shell: pwsh

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: pwsh

    - name: Run tests
      run: python test/autorization.py
