name: Install and Run .exe from ./bin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install .exe from ./bin
      run: |
        # Check if the bin directory exists
        if (-not (Test-Path -Path "./bin")) {
          Write-Output "Directory ./bin does not exist."
          Exit 1
        }

        # Path to the .exe file
        $exePath = "./bin/chromium-gost-125.0.6422.60-windows-amd64-installer.exe"

        # Check if the .exe file exists
        if (Test-Path -Path $exePath) {
          Write-Output "Executable found at $exePath"
          
          # Run the .exe file
          Start-Process -FilePath $exePath -ArgumentList "/silent" -Wait
          
          Write-Output "Executable ran successfully."
        } else {
          Write-Output "Executable not found at $exePath"
          Exit 1
        }

    - name: Run additional commands or tests
      shell: pwsh
      run: |
        # Replace this with your actual script or test commands
        Write-Output "Running additional commands or tests..."
        # Here you can run your PowerShell script or commands
        # For example, if you have a script located at ./scripts/test.ps1
        # .\scripts\test.ps1
