name: Install and Run Chromium-Gost

on:
  push:
    branches:
      - main

jobs:
  run-chromium-gost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List files in bin directory
        run: |
          ls -la bin

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ./bin/chromium-gost-126.0.6478.126-linux-amd64.deb

      - name: Verify installation
        run: |
          which chromium-browser
          chromium-browser --version

      - name: Run Chromium-Gost
        run: |
          nohup chromium-browser &

      - name: Run tests
        run: python test/autorization.py