name: Setup Browser on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup browser
      run: |
        # Create a directory for the browser if it doesn't exist
        if (-not (Test-Path -Path "./bin")) {
          New-Item -ItemType Directory -Path "./bin"
        }

        # Path to the browser executable
        $browserPath = "./bin/chromium-gost-125.0.6422.60-windows-amd64-installer.exe"

        # Check if the browser executable exists
        if (Test-Path -Path $browserPath) {
          Write-Output "Browser found at $browserPath"
        } else {
          Write-Output "Browser not found at $browserPath"
          Exit 1
        }

        # Optionally, you can add commands to install or configure the browser here
        # e.g., Copy the browser to a location in PATH or perform setup steps

        # Example: Installing the browser if needed
        # Start-Process -FilePath $browserPath -ArgumentList "/silent" -Wait

    - name: Run your script or tests
      run: |
        # Replace this with your actual script or test commands
        Write-Output "Running tests or other commands..."
