name: Run test

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install 7-Zip
      run: |
            choco install 7zip --no-progress

    - name: Download Chromium
      run: |
        curl -L -o Chromium.zip "https://cloud.mail.ru/public/jBUP/5jraqGLbR"
        Expand-Archive -Path Chromium.zip -DestinationPath C:\Chromium

    - name: Set up ChromeDriver
      run: |
        mkdir C:\chromedriver
        copy bin\chromedriver.exe C:\chromedriver\chromedriver.exe

    - name: Set up extension
      run: |
        mkdir C:\extensions
        copy extensions\1.2.13_0.crx C:\extensions\1.2.13_0.crx

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'  # Укажите необходимую версию Python

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run test
      run: |
        $env:CHROME_BIN="C:\Сhromium\Application\chrome.exe"
        $env:CHROME_DRIVER="C:\chromedriver\chromedriver.exe"
        pytest test/autorization.py