name: Test Automation

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Download Chromium.zip from Google Drive
      run: |
        $file_id = "17X8fPcJoY4tepOMSakJZslUwDspuD7z5"
        $file_name = "Chromium.zip"
        $base_url = "https://drive.google.com/uc?export=download&id=$file_id"
        
        # Get confirm token
        $response1 = Invoke-WebRequest -Uri $base_url -SessionVariable session -UseBasicParsing
        
        # Parse HTML content to get confirm token
        $htmlContent = [htmlagilitypack.htmlDocument]::new()
        $htmlContent.LoadHtml($response1.Content)
        $confirm_token = ($htmlContent.DocumentNode.SelectSingleNode("//a[contains(@href, 'confirm=')]").Attributes["href"].Value -split 'confirm=')[1]
        
        Write-Output "Response Content: $($response1.Content)"  # Логирование для отладки
        Write-Output "Confirm Token: $confirm_token"  # Логирование для отладки
        
        if (-not $confirm_token) {
            throw "Failed to get confirm token"
        }
        
        # Download file using confirm token
        $download_url = "$base_url&confirm=$confirm_token"
        Invoke-WebRequest -Uri $download_url -OutFile $file_name -WebSession $session -UseBasicParsing
        
        if (-Not (Test-Path -Path "$(Get-Location)\Chromium.zip")) { 
            throw "Chromium.zip not found" 
        }
        $fileInfo = Get-Item "$(Get-Location)\Chromium.zip"
        Write-Output "Chromium.zip size: $($fileInfo.Length) bytes"
        if ($fileInfo.Length -lt 100000) { # Assuming the file should be at least 100KB
            throw "Chromium.zip seems to be corrupted or incomplete"
        }
      shell: pwsh

    - name: Unzip Chromium.zip
      run: Expand-Archive -Path ./Chromium.zip -DestinationPath ./bin/Chromium
      shell: pwsh

    - name: Set up environment variables
      run: |
        $env:CHROME_BIN = "$(Get-Location)\bin\Chromium\Application\chrome.exe"
        $env:EXTENSION_CRX = "$(Get-Location)\extensions\1.2.13_0.crx"
        $env:EXTENSION_DRIVER = "$(Get-Location)\bin\chromedriver.exe"
      shell: pwsh

    - name: Verify files
      run: |
        if (-Not (Test-Path -Path "$(Get-Location)\bin\Chromium\Application\chrome.exe")) { throw "Chrome executable not found" }
        if (-Not (Test-Path -Path "$(Get-Location)\bin\chromedriver.exe")) { throw "Chromedriver not found" }
        if (-Not (Test-Path -Path "$(Get-Location)\extensions\1.2.13_0.crx")) { throw "Extension not found" }
      shell: pwsh

    - name: Run tests
      run: pytest test/autorization.py
      shell: pwsh
