name: Install and Run Chromium-Gost with Selenium

on:
  push:
    branches:
      - main

jobs:
  run-chromium-gost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List files in root directory
        run: |
          ls -la

      - name: List files in bin directory
        run: |
          ls -la bin

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb python3-pip ./bin/chromium-gost-126.0.6478.126-linux-amd64.deb
          pip3 install --upgrade urllib3 chardet
          pip3 install webdriver-manager  # Добавьте эту строку
          pip3 install --upgrade pip setuptools wheel
          

      - name: Установка CryptoPro CSP
        run: |
          cd ./bin
          tar -xzf linux-amd64_deb.tgz 
          cd linux-amd64_deb
          sudo ./install.sh

      - name: Create symbolic links for CryptoPro tools
        run: |
          sudo ln -s /opt/cprocsp/bin/amd64/certmgr /usr/local/bin/certmgr
          sudo ln -s /opt/cprocsp/bin/amd64/cpverify /usr/local/bin/cpverify
          sudo ln -s /opt/cprocsp/bin/amd64/cryptcp /usr/local/bin/cryptcp
          sudo ln -s /opt/cprocsp/bin/amd64/csptest /usr/local/bin/csptest
          sudo ln -s /opt/cprocsp/bin/amd64/csptestf /usr/local/bin/csptestf
          sudo ln -s /opt/cprocsp/bin/amd64/der2xer /usr/local/bin/der2xer
          sudo ln -s /opt/cprocsp/bin/amd64/inittst /usr/local/bin/inittst
          sudo ln -s /opt/cprocsp/bin/amd64/wipefile /usr/local/bin/wipefile
          sudo ln -s /opt/cprocsp/sbin/amd64/cpconfig /usr/local/bin/cpconfig

        # Установка необходимых пакетов CryptoPro CSP
           sudo apt-get update
           sudo apt-get install -y lsb-cprocsp-base lsb-cprocsp-rdr-64 lsb-cprocsp-kc1-64 lsb-cprocsp-capilite-64 cprocsp-curl-64 lsb-cprocsp-ca-certs
      - name: Install GTK2 library (libgtk2.0-0)
        run: sudo apt-get install -y libgtk2.0-0 libpangoxft-1.0-0
        # Установка rpm для работы с RPM-пакетами
      - name: Install cprocsp-rdr-gui-gtk-64 package
        run: |
          sudo dpkg -i ./bin/cprocsp-rdr-gui-gtk-64_4.0.0-4_amd64.deb
          sudo apt-get install -f -y


      - name: Extract CryptoPro EDS Browser plugin
        run: |
          sudo mkdir -p /opt/chromium-gost/plugin

      - name: Extract CryptoPro EDS Browser plugin
        run: |
          sudo tar -xvf ./bin/cades-linux-amd64.tar -C /opt/chromium-gost/plugin

      - name: Install CryptoPro EDS Browser plugin packages
        run: |
          cd /opt/chromium-gost/plugin/cades-linux-amd64
          sudo dpkg -i cprocsp-pki-cades-64_2.0.14892-1_amd64.deb
          sudo dpkg -i cprocsp-pki-plugin-64_2.0.14892-1_amd64.deb
          sudo apt-get install -f -y
            

      - name: Проверка сертификатов и установка
        run: |
            for cert in ./bin/*.cer; do
              openssl x509 -in "$cert" -out "${cert%.cer}.crt"
            done
            sudo cp ./bin/*.crt /usr/local/share/ca-certificates/
            sudo update-ca-certificates

      - name: Install dependencies
        run: |
         pip3 install -r requirements.txt
        shell: pwsh

      - name: Make chromedriver executable
        run: |
            chmod +x ./bin/chromedriver

      - name: Start Xvfb
        run: |
            Xvfb :99 -screen 0 1024x768x24 &
            export DISPLAY=:99
            echo "DISPLAY is set to $DISPLAY"
            ps -ef | grep Xvfb

      - name: Verify installation
        run: |
          which chromium-browser
          chromium-browser --version

      - name: Install Selenium
        run: |
          pip3 install selenium

      - name: Install Chromium-Gost Extension
        run: |
          mkdir -p $HOME/.config/chromium/Default/Extensions
          cp ./extensions/1.2.13_0.crx $HOME/.config/chromium/Default/Extensions/

      
  
          
          # Запуск Selenium тестов с установленным расширением и проверкой сертификатов
      - name: Run Selenium tests with Chromium-Gost Extension
        run: |
            chromium-browser --load-extension=./Extensions/1.2.13_0.crx 
            sleep 5
            python3 test/autorization.py
        env:
            DISPLAY: :99

          # Новый шаг для вывода параметров запуска и проверки сертификатов
      - name: Check Chromium-Gost parameters and certificates
        run: |
            echo "Chromium-Gost parameters:"
            ps aux | grep chromium-browser | grep -v grep || true  # Вывод параметров запуска, игнорируя сам grep процесса
          
            echo "Installed certificates:"
            ls /usr/local/share/ca-certificates/  # Проверка установленных сертификатов
          
            # Проверка наличия установленного расширения Chromium-Gost
            echo "Installed Chromium-Gost extension:"
            ls ./Extensions/1.2.13_0.crx || echo "Chromium-Gost extension not found"

        env:
          DISPLAY: :99