name: Install and Run Chromium-Gost with Selenium

on:
  push:
    branches:
      - main

jobs:
  run-chromium-gost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List files in root directory
        run: |
          ls -la

      - name: List files in bin directory
        run: |
          ls -la bin

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb python3-pip ./bin/chromium-gost-126.0.6478.126-linux-amd64.deb
          pip3 install --upgrade urllib3 chardet
          pip3 install webdriver-manager  # Добавьте эту строку
          pip3 install --upgrade pip setuptools wheel
          

      - name: Extract and Install CryptoPro CSP
        run: |
          cd ./bin
          tar -xzf linux-amd64_deb.tgz  # Замените на имя вашего архива, если нужно
          cd linux-amd64_deb
          sudo bash install.sh  # Если install.sh является установочным скриптом

      - name: Extract and Install Plugin
        run: |
         

      - name: Проверка сертификатов и установка
        run: |
            for cert in ./bin/*.cer; do
              openssl x509 -in "$cert" -out "${cert%.cer}.crt"
            done
            sudo cp ./bin/*.crt /usr/local/share/ca-certificates/
            sudo update-ca-certificates

      - name: Install dependencies
        run: |
         pip3 install -r requirements.txt
        shell: pwsh

      - name: Make chromedriver executable
        run: |
            chmod +x ./bin/chromedriver

      - name: Start Xvfb
        run: |
            Xvfb :99 -screen 0 1024x768x24 &
            export DISPLAY=:99
            echo "DISPLAY is set to $DISPLAY"
            ps -ef | grep Xvfb

      - name: Verify installation
        run: |
          which chromium-browser
          chromium-browser --version

      - name: Install Selenium
        run: |
          pip3 install selenium

      - name: Install Chromium-Gost Extension
        run: |
          mkdir -p $HOME/.config/chromium/Default/Extensions
          cp ./extensions/1.2.13_0.crx $HOME/.config/chromium/Default/Extensions/

      - name: Install and extract plugin
        run: |
          sudo mkdir -p /opt/chromium-gost/plugin
          sudo tar -xvf ./bin/cades-linux-amd64.tar -C /opt/chromium-gost/plugin/
          sudo chmod -R 755 /opt/chromium-gost/plugin/
          # Установите .deb файлы
          sudo dpkg -i /opt/chromium-gost/plugin/cades-linux-amd64/*.deb
          sudo apt-get install -f
                    
          # Запуск Selenium тестов с установленным расширением и проверкой сертификатов
      - name: Run Selenium tests with Chromium-Gost Extension
        run: |
            chromium-browser --load-extension=$HOME/.config/chromium/Default/Extensions/1.2.13_0.crx 
            sleep 5
            python3 test/autorization.py
        env:
            DISPLAY: :99

          # Новый шаг для вывода параметров запуска и проверки сертификатов
      - name: Check Chromium-Gost parameters and certificates
        run: |
            echo "Chromium-Gost parameters:"
            ps aux | grep chromium-browser | grep -v grep || true  # Вывод параметров запуска, игнорируя сам grep процесса
          
            echo "Installed certificates:"
            ls /usr/local/share/ca-certificates/  # Проверка установленных сертификатов
          
            # Проверка наличия установленного расширения Chromium-Gost
            echo "Installed Chromium-Gost extension:"
            ls $HOME/.config/chromium/Default/Extensions/1.2.13_0.crx || echo "Chromium-Gost extension not found"

        env:
          DISPLAY: :99