name: CI Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Chromium.zip
      run: |
        Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/210zl95t8jln4vg6lisrv/Chromium.zip?rlkey=66dk8nj43yw0qn3d9znszrnze&dl=1" -OutFile "C:\Chromium.zip"
      shell: pwsh

    - name: Unzip Chromium
      run: |
        Expand-Archive -Path "C:\Chromium.zip" -DestinationPath "C:\Chromium" -Force
      shell: pwsh

    - name: Copy extension.crx
      run: |
        Copy-Item -Path "./extension/1.2.13_0.crx" -Destination "C:\1.2.13_0.crx"
      shell: pwsh

    - name: Copy chromedriver.exe
      run: |
        Copy-Item -Path "./bin/chromedriver.exe" -Destination "C:\chromedriver.exe"
      shell: pwsh

    - name: Run tests
      run: |
        $CHROME_BIN = "C:\Chromium\Application\chrome.exe"
        $EXTENSION_CRX = "C:\1.2.13_0.crx"
        $EXTENSION_DRIVER = "C:\chromedriver.exe"
        
        # Установка переменных окружения
        $env:CHROME_BIN = $CHROME_BIN
        $env:EXTENSION_DRIVER = $EXTENSION_DRIVER
        $env:EXTENSION_CRX = $EXTENSION_CRX
        
        pytest test/autorization.py
      shell: pwsh
      env:
        pythonLocation: C:\hostedtoolcache\windows\Python\3.12.4\x64
