name: Extract and Run Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install 7-Zip
      run: |
        # Download and install 7-Zip
        Invoke-WebRequest -Uri https://www.7-zip.org/a/7z2201-x64.exe -OutFile 7z.exe
        Start-Process -FilePath .\7z.exe -ArgumentList "/S" -Wait

    - name: Extract chromium-gost archive
      run: |
        # Use 7-Zip to extract the archive
        & "C:\Program Files\7-Zip\7z.exe" x "./bin/chromium-gost-49.0.2623.112-win32-gold.7z" -o"./bin/chromium-gost" -y

    - name: Verify extracted files
      run: |
        # List files in the directory to verify extraction
        Get-ChildItem -Path "./bin/chromium-gost" -Recurse

    - name: Run chrome.exe
      run: |
        # Path to the chrome.exe file
        $chromePath = "./bin/chromium-gost-49.0.2623.112-win32/chrome.exe"
        
        # Check if the chrome.exe file exists
        if (Test-Path -Path $chromePath) {
          Write-Output "Executable found at $chromePath"
          
          # Run the browser in headless mode
          Start-Process -FilePath $chromePath -ArgumentList "--headless --disable-gpu --remote-debugging-port=9222" -Wait
          
          Write-Output "Browser is running in headless mode."
        } else {
          Write-Output "Executable not found at $chromePath"
          Exit 1
        }
      shell: pwsh
