name: Run test

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git LFS
      run: |
          git lfs install
          git lfs pull

    - name: Unzip Chromium.zip
      run: |
          Expand-Archive -Path ./bin/Chromium.zip -DestinationPath ./bin/Chromium
      shell: pwsh

    - name: Set up environment variables
      run: |
          $env:CHROME_BIN="$(pwd)/bin/Chromium/Application/chrome.exe"
          $env:EXTENSION_CRX="$(pwd)/extensions/1.2.13_0.crx"
          $env:EXTENSION_DRIVER="$(pwd)/bin/chromedriver.exe"
      shell: pwsh

    - name: Verify files
      run: |
              if (!(Test-Path -Path "$(pwd)/bin/Chromium/Application/chrome.exe")) { throw "Chrome executable not found" }
              if (!(Test-Path -Path "$(pwd)/bin/chromedriver.exe")) { throw "Chromedriver not found" }
              if (!(Test-Path -Path "$(pwd)/extensions/1.2.13_0.crx")) { throw "Extension not found" }
      shell: pwsh

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'  # Укажите необходимую версию Python

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up environment variables
      run: |
              $env:CHROME_BIN="$(pwd)/bin/Chromium/Application/chrome.exe"
              $env:EXTENSION_CRX="$(pwd)/extensions/1.2.13_0.crx
              $env:EXTENSION_DRIVER="$(pwd)/bin/chromedriver.exe
      shell: pwsh